-- Insert 100 additional yoga poses
INSERT INTO public.poses (name, description, duration_minutes, difficulty_level, category, instructions, benefits) VALUES
-- Standing Poses
('Warrior II', 'A strong standing pose that builds stamina and concentration', 1.5, 'beginner', 'standing', 'Step one foot back, bend front knee, extend arms parallel to floor', 'Strengthens legs, opens hips, improves focus'),
('Extended Side Angle', 'A lateral stretch from Warrior II position', 1.0, 'intermediate', 'standing', 'From Warrior II, place forearm on front thigh, reach top arm overhead', 'Stretches side body, strengthens legs'),
('Revolved Triangle', 'A twisted version of triangle pose', 2.0, 'advanced', 'standing', 'From wide-legged fold, twist and reach opposite hand to floor', 'Improves spinal mobility, aids digestion'),
('Eagle Pose', 'A balancing pose with arms and legs wrapped', 1.0, 'intermediate', 'balance', 'Wrap one leg around the other, entwine arms, balance', 'Improves concentration, stretches shoulders'),
('Tree Pose Variation', 'Tree pose with arms in different positions', 1.0, 'beginner', 'balance', 'Stand on one leg, place other foot on inner thigh, vary arm positions', 'Builds balance, strengthens standing leg'),
('Standing Forward Fold', 'A calming inversion while standing', 2.0, 'beginner', 'forward_fold', 'Hinge at hips, fold forward with straight legs', 'Calms nervous system, stretches hamstrings'),
('Wide-Legged Forward Fold', 'Forward fold with legs wide apart', 2.5, 'beginner', 'forward_fold', 'Stand with legs wide, fold forward from hips', 'Stretches inner thighs, calms mind'),
('Goddess Pose', 'A wide-legged squat with arms raised', 1.5, 'beginner', 'standing', 'Squat with feet wide and turned out, arms in cactus shape', 'Strengthens legs and core, opens hips'),
('High Lunge', 'A dynamic lunge position', 1.0, 'beginner', 'standing', 'Step one foot back, keep front knee over ankle, arms up', 'Strengthens legs, improves balance'),
('Low Lunge', 'A grounding lunge with back knee down', 1.5, 'beginner', 'standing', 'From high lunge, lower back knee to ground', 'Opens hip flexors, builds stability'),

-- Seated Poses
('Easy Pose', 'A comfortable cross-legged seated position', 3.0, 'beginner', 'seated', 'Sit cross-legged with straight spine', 'Calms mind, improves posture'),
('Lotus Pose', 'An advanced seated meditation pose', 5.0, 'advanced', 'seated', 'Cross legs with feet on opposite thighs', 'Deep hip opening, traditional meditation pose'),
('Half Lotus', 'A modified lotus pose', 3.0, 'intermediate', 'seated', 'Cross legs with one foot on opposite thigh', 'Hip opening, meditation preparation'),
('Bound Angle Pose', 'Seated with soles of feet together', 2.0, 'beginner', 'seated', 'Sit with soles of feet together, gently fold forward', 'Opens hips, stretches inner thighs'),
('Seated Spinal Twist', 'A seated twist for spinal mobility', 1.5, 'beginner', 'twist', 'Sit with one leg extended, cross other leg over, twist', 'Improves spinal mobility, aids digestion'),
('Marichyasana C', 'A seated binding twist', 2.0, 'intermediate', 'twist', 'Seated twist with arm binding around bent leg', 'Deep spinal twist, shoulder mobility'),
('Compass Pose', 'An advanced seated side stretch', 2.0, 'advanced', 'seated', 'Seated with one leg extended overhead in hand', 'Extreme flexibility, hamstring stretch'),
('Fire Log Pose', 'Seated with shins stacked', 2.5, 'intermediate', 'seated', 'Stack shins parallel to each other, fold forward', 'Deep hip opening, releases tension'),
('Hero Pose', 'Kneeling between the feet', 2.0, 'beginner', 'seated', 'Kneel and sit between your feet', 'Stretches thighs, improves digestion'),
('Reclined Hero', 'Hero pose lying back', 3.0, 'intermediate', 'seated', 'From hero pose, slowly recline backwards', 'Deep thigh stretch, opens chest'),

-- Backbends
('Camel Pose', 'A deep backbend on the knees', 1.0, 'intermediate', 'backbend', 'Kneel, reach back to grab heels, open chest', 'Opens chest and hip flexors, energizing'),
('Wheel Pose', 'A full backbend from lying down', 1.5, 'advanced', 'backbend', 'Lie down, press up into full backbend', 'Strengthens arms and legs, opens entire front body'),
('Fish Pose', 'A gentle backbend lying down', 2.0, 'beginner', 'backbend', 'Lie with forearms down, arch back and open chest', 'Opens chest, stretches neck'),
('Bridge Pose', 'A backbend lifting hips from lying down', 1.0, 'beginner', 'backbend', 'Lie down, bend knees, lift hips up', 'Strengthens glutes, opens chest'),
('Upward Facing Dog', 'An arm-supported backbend', 0.5, 'intermediate', 'backbend', 'From plank, roll over toes, straighten arms', 'Strengthens arms, opens chest'),
('Bow Pose', 'A backbend holding the feet', 1.0, 'intermediate', 'backbend', 'Lie on belly, grab feet, rock forward', 'Opens entire front body, strengthens back'),
('Scorpion Pose', 'An advanced inverted backbend', 1.0, 'advanced', 'inversion', 'Forearm stand with feet arching over head', 'Advanced inversion, extreme flexibility'),
('King Pigeon', 'An advanced hip opener with backbend', 2.0, 'advanced', 'backbend', 'From pigeon, grab back foot and arch into backbend', 'Deep hip and chest opening'),
('Dancer Pose', 'A standing backbend balancing on one leg', 1.0, 'intermediate', 'balance', 'Stand on one leg, grab other foot behind, arch back', 'Improves balance, opens chest and hips'),
('Sphinx Pose', 'A gentle prone backbend', 2.0, 'beginner', 'backbend', 'Lie on belly, prop up on forearms', 'Gentle backbend, strengthens back muscles'),

-- Core Poses
('Boat Pose', 'A V-shaped core strengthener', 1.0, 'intermediate', 'core', 'Sit, lift legs and arms to form V-shape', 'Strengthens core, improves balance'),
('Hollow Body', 'A core pose lying on back', 1.0, 'intermediate', 'core', 'Lie on back, press lower back down, lift shoulders and legs', 'Strengthens entire core'),
('Side Plank', 'A lateral core strengthener', 1.0, 'intermediate', 'core', 'From plank, roll to one side, stack feet and lift hips', 'Strengthens obliques, improves stability'),
('Crow Pose', 'An arm balance with knees on arms', 1.0, 'intermediate', 'balance', 'Squat, place hands down, balance knees on upper arms', 'Builds arm strength, improves focus'),
('Firefly Pose', 'An advanced arm balance', 1.0, 'advanced', 'balance', 'From squat, thread arms under legs, balance', 'Advanced arm balance, core strength'),
('Eight-Angle Pose', 'A complex arm balance with legs to one side', 1.0, 'advanced', 'balance', 'Arm balance with both legs hooked around one arm', 'Extreme arm strength and flexibility'),
('Plank Pose', 'A foundational arm and core strengthener', 1.0, 'beginner', 'core', 'Hold push-up position with straight body', 'Strengthens arms, core, and legs'),
('Chaturanga', 'A low push-up position', 0.5, 'intermediate', 'core', 'Lower from plank with elbows close to ribs', 'Builds arm and core strength'),
('Dolphin Pose', 'A forearm stand preparation', 1.0, 'intermediate', 'core', 'Downward dog on forearms', 'Strengthens shoulders, prepares for inversions'),
('Twisted Boat', 'Boat pose with spinal rotation', 1.0, 'intermediate', 'twist', 'From boat pose, twist torso side to side', 'Strengthens core with rotation'),

-- Forward Folds
('Seated Forward Bend', 'A calming seated forward fold', 3.0, 'beginner', 'forward_fold', 'Sit with legs extended, fold forward over legs', 'Calms nervous system, stretches back'),
('Head to Knee Pose', 'Forward fold over one extended leg', 2.0, 'beginner', 'forward_fold', 'Sit with one leg bent, fold over extended leg', 'Stretches hamstrings, calms mind'),
('Revolved Head to Knee', 'A twisted version of head to knee pose', 2.0, 'intermediate', 'twist', 'From head to knee, twist and reach top arm over', 'Spinal twist, side body stretch'),
('Double Pigeon Forward Fold', 'Forward fold from double pigeon pose', 2.5, 'intermediate', 'forward_fold', 'Stack shins, fold forward', 'Deep hip opening, calming'),
('Turtle Pose', 'An advanced forward fold with arms under legs', 2.0, 'advanced', 'forward_fold', 'Thread arms under bent legs, fold forward deeply', 'Extreme forward fold, introspective'),
('Monkey Pose', 'Full splits with forward fold', 3.0, 'advanced', 'forward_fold', 'Full front splits, fold forward over front leg', 'Extreme hamstring and hip flexor stretch'),
('Standing Split', 'Forward fold balancing on one leg', 1.0, 'intermediate', 'balance', 'Fold forward, lift one leg high behind you', 'Hamstring stretch, improves balance'),
('Pyramid Pose', 'A forward fold over one leg', 1.5, 'beginner', 'forward_fold', 'Step one foot back, fold over front leg', 'Stretches hamstrings, calms mind'),
('Intense Side Stretch', 'A forward fold between two legs', 2.0, 'intermediate', 'forward_fold', 'Stand with feet wide, fold forward and to one side', 'Asymmetrical stretch, spinal mobility'),
('Ragi Pose', 'A deep forward fold in lotus', 3.0, 'advanced', 'forward_fold', 'From lotus, fold deeply forward', 'Advanced hip opening with forward fold'),

-- Inversions
('Headstand', 'The king of yoga poses', 3.0, 'advanced', 'inversion', 'Balance on crown of head with forearm support', 'Reverses blood flow, builds strength'),
('Forearm Stand', 'An inversion on the forearms', 2.0, 'advanced', 'inversion', 'Balance on forearms with legs up', 'Builds shoulder strength, improves focus'),
('Handstand', 'A full arm balance inversion', 1.0, 'advanced', 'inversion', 'Balance on hands with legs up', 'Ultimate arm strength, conquers fear'),
('Shoulder Stand', 'A supported inversion', 3.0, 'intermediate', 'inversion', 'Lie down, lift legs overhead, support lower back', 'Gentle inversion, calms nervous system'),
('Legs Up the Wall', 'A restorative inversion', 5.0, 'beginner', 'relaxation', 'Lie with legs up against wall', 'Deeply relaxing, improves circulation'),
('Plow Pose', 'An inversion with toes touching behind head', 2.0, 'intermediate', 'inversion', 'From shoulder stand, lower toes to floor behind head', 'Stimulates thyroid, stretches spine'),
('Supported Headstand', 'Headstand with wall support', 2.0, 'intermediate', 'inversion', 'Headstand against wall for support', 'Builds confidence for freestanding headstand'),
('Pincha Mayurasana', 'Forearm stand with chest opening', 1.5, 'advanced', 'inversion', 'Forearm stand with deep chest opening', 'Advanced inversion with backbend'),
('Hollow Back Handstand', 'Handstand with arched back', 1.0, 'advanced', 'inversion', 'Handstand with chest opening and arched spine', 'Combines inversion with extreme backbend'),
('Side Crow', 'Crow pose with legs to one side', 1.0, 'advanced', 'balance', 'From crow, shift legs to one side', 'Advanced arm balance with asymmetry'),

-- Twists
('Bharadvajasana', 'A seated twist with legs to one side', 2.0, 'intermediate', 'twist', 'Sit with legs to one side, twist toward bent knees', 'Gentle spinal twist, improves digestion'),
('Simple Twisted Lunge', 'A lunge with spinal rotation', 1.0, 'beginner', 'twist', 'From lunge, place opposite hand down, reach other arm up', 'Opens chest, twists spine'),
('Revolved Side Angle', 'A twisted version of side angle pose', 1.5, 'intermediate', 'twist', 'From warrior II, twist and reach bottom arm under front leg', 'Deep twist, challenges balance'),
('Twisted Triangle', 'Triangle pose with opposite hand down', 1.5, 'intermediate', 'twist', 'From wide legs, twist and reach opposite hand to floor', 'Spinal mobility, liver stimulation'),
('Revolved Chair', 'Chair pose with a twist', 1.0, 'intermediate', 'twist', 'From chair pose, twist and bring elbow to opposite knee', 'Combines strength with spinal mobility'),
('Eagle Twist', 'A twisted variation of eagle pose', 1.0, 'intermediate', 'twist', 'From eagle pose, twist torso to deepen the pose', 'Challenges balance with rotation'),
('Twisted Warrior III', 'Warrior III with spinal rotation', 1.0, 'advanced', 'twist', 'From warrior III, open arms and twist torso', 'Advanced balance with spinal mobility'),
('Sage Twist', 'A deep seated twist with leg binding', 2.0, 'advanced', 'twist', 'Complex seated twist with one leg bent and bound', 'Deep spinal rotation, hip opening'),
('Twisted Lizard', 'Lizard pose with a twist', 1.5, 'intermediate', 'twist', 'From lizard pose, reach one arm up and twist', 'Hip opening with spinal rotation'),
('Revolved Crescent', 'Crescent lunge with a twist', 1.0, 'intermediate', 'twist', 'From crescent lunge, twist and bring hands to prayer', 'Dynamic pose combining strength and mobility'),

-- Hip Openers
('Pigeon Pose', 'A deep hip opener', 3.0, 'intermediate', 'seated', 'One leg forward bent, other leg extended back', 'Deep hip opening, emotional release'),
('Double Pigeon', 'Both shins parallel for hip opening', 2.0, 'intermediate', 'seated', 'Stack shins parallel to each other', 'Bilateral hip opening'),
('Lizard Pose', 'A low lunge hip opener', 2.0, 'beginner', 'standing', 'Low lunge with forearms on ground inside front leg', 'Opens hips and groin'),
('Frog Pose', 'A wide-knee hip opener', 2.0, 'intermediate', 'seated', 'Kneel with knees wide, forearms on ground', 'Deep groin opening'),
('Cow Face Pose', 'Legs stacked hip opener', 2.0, 'intermediate', 'seated', 'Sit with knees stacked, one foot by opposite hip', 'Hip and shoulder opener'),
('Lotus Preparation', 'Building toward lotus pose', 2.0, 'intermediate', 'seated', 'Various leg positions preparing for lotus', 'Gradual hip opening'),
('Happy Baby', 'A playful supine hip opener', 2.0, 'beginner', 'relaxation', 'Lie on back, hold feet, rock gently', 'Gentle hip opening, stress relief'),
('Garland Pose', 'A deep squat', 2.0, 'beginner', 'standing', 'Deep squat with feet close together', 'Opens hips, aids elimination'),
('Twisted Dragon', 'Dragon pose with spinal twist', 2.0, 'intermediate', 'twist', 'From dragon pose, add spinal rotation', 'Hip opening with twist'),
('Swan Pose', 'An advanced pigeon variation', 2.0, 'advanced', 'seated', 'Pigeon with deep forward fold and quad stretch', 'Extreme hip opening'),

-- Relaxation & Restorative (20 poses to reach 100 total)
('Corpse Pose', 'The ultimate relaxation pose', 10.0, 'beginner', 'relaxation', 'Lie flat, completely relax all muscles', 'Deep rest, integration'),
('Supported Child Pose', 'Child pose with props', 5.0, 'beginner', 'relaxation', 'Child pose with bolster or blanket support', 'Deeply nurturing, stress relief'),
('Reclined Butterfly', 'Bound angle pose lying down', 5.0, 'beginner', 'relaxation', 'Lie back with soles of feet together', 'Gentle hip opening, very relaxing'),
('Supported Fish', 'Fish pose with bolster support', 5.0, 'beginner', 'relaxation', 'Fish pose with props supporting the back', 'Heart opening, deeply restorative'),
('Yoga Nidra Pose', 'Body scan relaxation position', 20.0, 'beginner', 'relaxation', 'Comfortable lying position for guided relaxation', 'Deep meditation, stress relief'),
('Supported Twist', 'Gentle twist with prop support', 5.0, 'beginner', 'relaxation', 'Side-lying twist with bolster between legs', 'Gentle spinal release'),
('Restorative Forward Fold', 'Forward fold with full support', 5.0, 'beginner', 'relaxation', 'Seated forward fold with head supported', 'Calming, introspective'),
('Supported Backbend', 'Gentle backbend with bolster', 5.0, 'beginner', 'relaxation', 'Lie back over bolster for gentle chest opening', 'Heart opening, energizing'),
('Side-Lying Savasana', 'Corpse pose on the side', 10.0, 'beginner', 'relaxation', 'Lie on side with props for comfort', 'Alternative to traditional savasana'),
('Meditation Pose', 'Comfortable seated position for meditation', 10.0, 'beginner', 'seated', 'Any comfortable cross-legged position', 'Mental clarity, spiritual connection');