// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqyoksafipjajbwosauh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxeW9rc2FmaXBqYWpid29zYXVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDAzOTUsImV4cCI6MjA2NzA3NjM5NX0.ngk0EWnE0t_jC6dhk59QTQeLVNJhcAtL3hLw8n6EJ7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});